apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      name: myapp

  template:
    metadata:
      name: myapp-pod
      labels:
        name: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx